export const NEW_ROUND = 'NEW_ROUND';
export const UPDATE_CURRENT_LETTER = 'UPDATE_CURRENT_LETTER';
export const UPDATE_LETTERS_CORRECT = 'UPDATE_LETTERS_CORRECT';
export const UPDATE_LETTERS_INCORRECT = 'UPDATE_LETTERS_INCORRECT';
export const END_ROUND =
'END_ROUND';
